### PR TITLE
Add OS X Mojave-specific build / link config

### PR DESCRIPTION
**Pull request by wileykestner**
- add OS X Mojave to the list of platforms which require `/usr/local/include` to be in `include_dirs`
- add OS X Mojave to the list of platforms which require `/usr/local/lib` to be in `library_dirs`

### CODE REVIEW

**Comment by jalan** [comment]
I haven't updated to Mojave yet, but shouldn't `/usr/local` be included in the default search paths on macOS? I suspect something went wrong with your upgrade.

**Comment by wileykestner** [comment]
It's entirely possible that there is something idiosyncratic about my setup.  Any recommendations on how to compare the library and header search paths that my system is using to your setup or a "bare" installation of mojave?  I am using Xcode Version 10.1 10B61.

Here's the brief history of the changes in this change set and how I arrived at them.

I proposed this change set because I could not use `pip` to install `pdftotext` on my machine after following the instructions in the `README`.

When I tried to install with `pip install pdftotext`, `clang` failed when trying to compile the native extension.

First, `clang` could not find the headers for `poppler` so it failed at the compilation step.  

After I added the explicit header search path in `setup.py`, `clang` made it past the first error, but then raised a second compiler error.  

The second error suggested that you now have to specify version of the C++ standard library that you'd like to compile against, so I added that flag in `setup.py` as well.  That resolved the second error on my machine.

Once the `std=c++11` flag was specified, `clang` was able to make it past the compilation step for the native extension, but still raised an error because it could not find the built `poppler` library to link against, so it failed at the link step.  So I added the explicit library search path to `setup.py` and that allowed the native extension to compile successfully.

Only after I added all three fixes was I then able to successfully run `pip install pdftotext` and use the library.  I tested on my machine using both python 2 and python 3.

I'm open to your guidance on how to proceed, thanks for publishing this useful library!

**Comment by jalan** [comment]
> It's entirely possible that there is something idiosyncratic about my setup. Any recommendations on how to compare the library and header search paths that my system is using to your setup or a "bare" installation of mojave? I am using Xcode Version 10.1 10B61.

You could try `cpp -v` on your system vs on a new Mojave system, if you have one to test on. Here is the output from my High Sierra 10.13.6 system, for reference:

```
$ cpp -v
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
 "/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.13.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -target-linker-version 409.12 -v -resource-dir /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0 -I /usr/include -fdebug-compilation-dir /Users/jason -ferror-limit 19 -fmessage-length 128 -stack-protector 1 -fblocks -fencode-extended-block-signature -fobjc-runtime=macosx-10.13.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -traditional-cpp -o - -x c -
clang -cc1 version 10.0.0 (clang-1000.10.44.4) default target x86_64-apple-darwin17.7.0
ignoring duplicate directory "/usr/include"
  as it is a non-system directory that duplicates a system directory
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include
 /Library/Developer/CommandLineTools/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
^C
```

You can also ask `brew` which version of the Xcode Command Line Tools it sees. Here is mine for reference:

```
$ brew config
HOMEBREW_VERSION: 1.8.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 858c5e1afb0eb00079a4f014e8fbedf9065d50e4
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5ffc6f250d04e8b337466dacedb4a249c57cf1e6
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

You might also run `brew doctor` to see if it notices any issues.

**Comment by wileykestner** [comment]
Thanks very much for the helpful suggestions.

After some more exploration, it seems as if the issues I'm experiencing only happen when I try to `pip install pdftotext` within a `virtualenv`.   I am able to install `pdftotext==2.1.1` fine when I'm outside of the `virtualenv` using `pip install pdftotext`.

Naively I would assume something about being inside that `virtualenv` is messing with the contents of the environment variables that `clang` needs to find the header search paths and the library search paths.

When I'm inside my activated `virtualenv` here is the output I get from `brew doctor`:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/wiley/workspace/pdftotext-test/env/bin/python-config
```

Here are the contents of that script.  Note the parts that deal with with header search paths and library paths - this looks very related to the issues I'm experiencing when inside the `virtualenv`:

```python3
#!/Users/wiley/workspace/pdftotext-test/env/bin/python

import sys
import getopt
import sysconfig

valid_opts = ['prefix', 'exec-prefix', 'includes', 'libs', 'cflags',
              'ldflags', 'help']

if sys.version_info >= (3, 2):
    valid_opts.insert(-1, 'extension-suffix')
    valid_opts.append('abiflags')
if sys.version_info >= (3, 3):
    valid_opts.append('configdir')


def exit_with_usage(code=1):
    sys.stderr.write("Usage: {0} [{1}]\n".format(
        sys.argv[0], '|'.join('--'+opt for opt in valid_opts)))
    sys.exit(code)

try:
    opts, args = getopt.getopt(sys.argv[1:], '', valid_opts)
except getopt.error:
    exit_with_usage()

if not opts:
    exit_with_usage()

pyver = sysconfig.get_config_var('VERSION')
getvar = sysconfig.get_config_var

opt_flags = [flag for (flag, val) in opts]

if '--help' in opt_flags:
    exit_with_usage(code=0)

for opt in opt_flags:
    if opt == '--prefix':
        print(sysconfig.get_config_var('prefix'))

    elif opt == '--exec-prefix':
        print(sysconfig.get_config_var('exec_prefix'))

    elif opt in ('--includes', '--cflags'):
        flags = ['-I' + sysconfig.get_path('include'),
                 '-I' + sysconfig.get_path('platinclude')]
        if opt == '--cflags':
            flags.extend(getvar('CFLAGS').split())
        print(' '.join(flags))

    elif opt in ('--libs', '--ldflags'):
        abiflags = getattr(sys, 'abiflags', '')
        libs = ['-lpython' + pyver + abiflags]
        libs += getvar('LIBS').split()
        libs += getvar('SYSLIBS').split()
        # add the prefix/lib/pythonX.Y/config dir, but only if there is no
        # shared library in prefix/lib/.
        if opt == '--ldflags':
            if not getvar('Py_ENABLE_SHARED'):
                libs.insert(0, '-L' + getvar('LIBPL'))
            if not getvar('PYTHONFRAMEWORK'):
                libs.extend(getvar('LINKFORSHARED').split())
        print(' '.join(libs))

    elif opt == '--extension-suffix':
        ext_suffix = sysconfig.get_config_var('EXT_SUFFIX')
        if ext_suffix is None:
            ext_suffix = sysconfig.get_config_var('SO')
        print(ext_suffix)

    elif opt == '--abiflags':
        if not getattr(sys, 'abiflags', None):
            exit_with_usage()
        print(sys.abiflags)

    elif opt == '--configdir':
        print(sysconfig.get_config_var('LIBPL'))
```

When I'm inside my activated `virtualenv` here is the output I get from `cpp -v`:
```sh
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.14.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -target-linker-version 409.12 -v -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0 -I /usr/include -fdebug-compilation-dir /Users/wiley/workspace/pdftotext-test -ferror-limit 19 -fmessage-length 189 -stack-protector 1 -fblocks -fencode-extended-block-signature -fobjc-runtime=macosx-10.14.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -traditional-cpp -o - -x c -
clang -cc1 version 10.0.0 (clang-1000.11.45.5) default target x86_64-apple-darwin18.2.0
ignoring duplicate directory "/usr/include"
  as it is a non-system directory that duplicates a system directory
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
```

Finally, here is the error output of `pip install pdftotext` when I'm inside my activated `virtualenv`:

```
Collecting pdftotext
  Using cached https://files.pythonhosted.org/packages/21/35/60094dbadd9de2035873390b1cac25e01da605844eba6a07a53a82fa4adc/pdftotext-2.1.1.tar.gz
Building wheels for collected packages: pdftotext
  Running setup.py bdist_wheel for pdftotext ... error
  Complete output from command /Users/wiley/workspace/pdftotext-test/env/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/jp/mxw37jkx02b88lv87493zxgr0000gp/T/pip-install-xt4zv63u/pdftotext/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/jp/mxw37jkx02b88lv87493zxgr0000gp/T/pip-wheel-f1f_ydyf --python-tag cp37:
  running bdist_wheel
  running build
  running build_ext
  building 'pdftotext' extension
  creating build
  creating build/temp.macosx-10.14-x86_64-3.7
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DPOPPLER_CPP_AT_LEAST_0_30_0=1 -I/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c pdftotext.cpp -o build/temp.macosx-10.14-x86_64-3.7/pdftotext.o -Wall -mmacosx-version-min=10.9
  pdftotext.cpp:3:10: fatal error: 'poppler/cpp/poppler-document.h' file not found
  #include <poppler/cpp/poppler-document.h>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1

  ----------------------------------------
  Failed building wheel for pdftotext
  Running setup.py clean for pdftotext
Failed to build pdftotext
Installing collected packages: pdftotext
  Running setup.py install for pdftotext ... error
    Complete output from command /Users/wiley/workspace/pdftotext-test/env/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/jp/mxw37jkx02b88lv87493zxgr0000gp/T/pip-install-xt4zv63u/pdftotext/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/jp/mxw37jkx02b88lv87493zxgr0000gp/T/pip-record-gdo_i7mr/install-record.txt --single-version-externally-managed --compile --install-headers /Users/wiley/workspace/pdftotext-test/env/bin/../include/site/python3.7/pdftotext:
    running install
    running build
    running build_ext
    building 'pdftotext' extension
    creating build
    creating build/temp.macosx-10.14-x86_64-3.7
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DPOPPLER_CPP_AT_LEAST_0_30_0=1 -I/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c pdftotext.cpp -o build/temp.macosx-10.14-x86_64-3.7/pdftotext.o -Wall -mmacosx-version-min=10.9
    pdftotext.cpp:3:10: fatal error: 'poppler/cpp/poppler-document.h' file not found
    #include <poppler/cpp/poppler-document.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1

    ----------------------------------------
Command "/Users/wiley/workspace/pdftotext-test/env/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/jp/mxw37jkx02b88lv87493zxgr0000gp/T/pip-install-xt4zv63u/pdftotext/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/jp/mxw37jkx02b88lv87493zxgr0000gp/T/pip-record-gdo_i7mr/install-record.txt --single-version-externally-managed --compile --install-headers /Users/wiley/workspace/pdftotext-test/env/bin/../include/site/python3.7/pdftotext" failed with error code 1 in /private/var/folders/jp/mxw37jkx02b88lv87493zxgr0000gp/T/pip-install-xt4zv63u/pdftotext/
```
So at this point, my working hypothesis is that activating the `virtualenv` is the source of this issue.  I think a lot of folks do use isolated `virtualenv`s to do their python development and application deployment so I would vote for supporting `pip` installs of `pdftotext` within isolated `virtualenv`s.  If there is a way to configure an isolated `virtualenv` such that clang can still see the same header and library search paths inside of `virtualenv` as outside, I don't know it - but I'm no expert so I would need guidance, perhaps someone like @carljm might be kind enough to share some knowledge.

If there is no extra configuration that can be added to a `virtualenv` to maintain its isolation but still allow `clang` to "see" the same header / library search paths inside the `virtualenv` as outside, at least part of this pull request may still be useful for supporting users who wish to install `pdftotext` within an isolated `virtualenv`.  I look forward to any thoughts or guidance you had on the matter and would be more than happy to update the pull request to better support this use case.

**Comment by jalan** [comment]
Thanks for all the troubleshooting!

That `python-config` script is a false alarm--looks normal to me.

Installing inside a virtualenv is of course the recommended way to go and has always been supported.

Until I get further evidence that this is broken for more macOS 10.14 users and not just you, I'm going to hold off on any changes. I hope to upgrade my own system to 10.14 soon. Otherwise I need to find someone else to help investigate.

**Comment by wileykestner** [comment]
FYI - I just had a friend do a test install inside of an isolated `virtualenv` on OS X Mojave and the friend experienced the same issue that I did.  Let me know how your upgrade to Mojave goes and if you also experience this issue, if this PR solves it for you.

**Comment by rob-h-w** [comment]
+1 I see this issue as well.

**Comment by wileykestner** [comment]
@rob-h-w Did this PR work for you as a fix?

**Comment by rob-h-w** [comment]
> @rob-h-w Did this PR work for you as a fix?

Hi @wileykestner. Yes, the PR worked as expected. I"m using it for local development until it can get merged.

**Comment by wileykestner** [comment]
@jalan Looks like there's at least one other case of this in the wild.  Have you done an update to Mojave?  Were you able to reproduce the issue?

**Comment by jalan** [comment]
I have a Mojave system here now, and everything works fine without this PR, using all of
 - python 2.7.16 from brew
 - python 3.7.2 from brew
 - python 2.7.10 from /usr/bin

Let me know if there's any system information you want to compare, to see if we can find where the difference is

**Comment by wileykestner** [comment]
@jalan I'm on macOS version 10.14.3, I see that there is a 10.14.4 update available (as of yesterday I think).  Which version of macOS are you running?

**Comment by jalan** [comment]
I'm on 10.14.1 now. I will update to 10.14.4 and report back.

**Comment by dima-kov** [comment]
+1 same error.
Installed only from PR.
Mojave 10.14.4

**Comment by jalan** [comment]
Tested again on Mojave 10.14.5, and everything works fine without this PR, using all of

 - python 2.7.16 from brew
 - python 3.7.3 from brew
 - python 2.7.10 from /usr/bin

I have to believe that there's something wrong with your build environments ☹️ . Maybe the Xcode command line tools are missing? `xcode-select --install`

For reference, here are the include paths that I get from `cpp -v`:

```
#include <...> search starts here:
 /usr/local/include
 /Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include
 /Library/Developer/CommandLineTools/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks (framework directory)
End of search list.
```

**Comment by SachaMPS** [comment]
I can report that on OSX Mojave 10.14.5 after a fresh install in virtualenv the same problems occured and I was only able to get everything working with this PR. 

* python 3.7.3 from brew

The only change i made recently to my system (as far as i am aware) was that i had to update XCode to Version 10.2.1.

**Comment by jalan** [comment]
@SachaMPS Could you post the output of `brew config` and `cpp -v` and `xcode-select -p` from inside that virtual environment? Might help finally find the cause of this weirdness.

**Comment by SachaMPS** [comment]
@jalan Here they are:

brew config:
```
HOMEBREW_VERSION: 2.1.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: fddf5b16bd8df577380a1d810d17825ef611b81f
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 940d65f062abea4ba1bc62f3e75e05ec996ccc62
Core tap last commit: 4 days ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.22.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
CLT headers: 10.2.1.0.1.1554506761
```

cpp -v:
```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.14.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-sdk-version=10.14 -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -target-linker-version 450.3 -v -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I /usr/include -I/usr/local/include -Wno-atomic-implicit-seq-cst -Wno-framework-include-private-from-public -Wno-atimport-in-framework-header -Wno-quoted-include-in-framework-header -fdebug-compilation-dir /Users/smps/Mllrsohn/imageaimobile.beta -ferror-limit 19 -fmessage-length 117 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=macosx-10.14.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -traditional-cpp -o - -x c -
clang -cc1 version 10.0.1 (clang-1001.0.46.4) default target x86_64-apple-darwin18.6.0
ignoring nonexistent directory "/usr/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks (framework directory)
End of search list.
```

xcode-select -p:
```
/Applications/Xcode.app/Contents/Developer
```

**Comment by jalan** [comment]
@SachaMPS Thanks for that info!

**Comment by rob-h-w** [comment]
I'm still able to reproduce this with Mojave 10.14.5, pdftotext 2.1.1 & Python 3.7.3.

**Comment by jalan** [comment]
I finally set up Xcode and was able to reproduce this. Should be fixed in v2.1.2, which I just pushed to PyPI.

Thanks, everyone!

**Pull request closed without merging**
