### PR TITLE
Closes #16 Cannot install on windows - Patch

### LINKED ISSUE #16: Cannot Install on Windows 10
I am running Win10 with the anaconda dist of python 3.6 and have the MS build tools and compiler installed.  I pip install the pdftotext package.  Installation begins and then terminates with this message:

```
pdftotext.cpp(3): fatal error C1083: Cannot open include file: 'poppler/cpp/poppler-document.h': No such file or directory
```

Any ideas?

### PR DESCRIPTION
**Pull request by woodsjs**
Fixes issue where install looks for poppler lib and include in different directory than Anaconda installed it. 
Updates readme with install instructions for Windows.

### CODE REVIEW

**Comment by jalan** [comment]
Thanks! This should be a big help to the people who have asked for Windows support in the past.

I wonder if I can set up AppVeyor to automatically test the Windows build.

In any case, I plan to merge this shortly.

**Comment by woodsjs** [comment]
Great!  As for AppVeyor, it looks like there is support for Miniconda/Miniconda3 which this patch works with. It also looks like you can enable c++ tools in the yml file. 
I don't have any personal experience with AppVeyor, but should be doable.

**Comment by RVerma93** [comment]
First off, big thanks to everybody for contributing to fixing this. 

I'm getting this in perpetuity when trying to forge poppler.

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed

Any ideas?

**Comment by woodsjs** [comment]
Hey @RVerma93 have you tried 
`conda install -c conda-forge poppler`
That usually works.

**Comment by RVerma93** [comment]
@woodsjs thanks for the reply. I've run that same command- no luck, I think there are dependencies that it doesn't like, the command is perpetually running even after 20 minutes. The setup.py file step is something I feel like i'm missing. What exactly needs to be done with that? Thanks

**Comment by woodsjs** [comment]
Hey @RVerma93 thanks for the screenshot.  There's a reported issue with conda documented here [https://github.com/conda/conda/issues/9367](https://github.com/conda/conda/issues/9367) that outlines the issue you're having with some workarounds.  It looks like it might be conflicts between the conda version and python version. You might want to follow some of the advice there for resolving the issue (downgrade or create venv specifying python version).

For the setup.py,  clone the master branch of this repo, You'll need MS Visual C++ libraries installed as well. Move into the pdftotext directory created when you cloned it. If you `pip search pdftotext` you'll probably see just the package listed with no install.  Run `python setup.py install`.  If all goes well pdftotext should be built and you'll have the globally installed package, verified with the `pip search pdftotext` command which should give you an INSTALLED line with the current version.

**Comment by RVerma93** [comment]
@woodsjs Thank you! It was as simple as playing around with the conda versions, it seems like the newest version of conda did the trick, and the rest was as instructed. For those facing similar issues, simply run `conda update --all` and see if that works. Thanks again!

**Pull request merged**
